### PR TITLE
Fix broken test

### PR DESCRIPTION
**Pull request by ancorgs**
Trying to fix https://build.opensuse.org/package/live_build_log/openSUSE:Factory:Staging:H/yast2-network/standard/i586

### CODE REVIEW

**Comment by mchf** [comment]
Well this doesn't explain why the test passes on x86_64 and fails only on i586

**Comment by ancorgs** [comment]
That made it a fragile test in general. With potential to fail in different ways in different systems. For example, in my workstation ruby crashed after running the tests, but it does not crash any more with this fix.

**Comment by mchf** [comment]
can be. In general I've nothing against this fix. It it helps it would be nice. There was no change in this code for some time and I didn't find anything arch specific what could influence the test. So LGTM once travis is happy.

**Comment by mchf** [comment]
rebased and merged as PR#419

**Pull request closed without merging**
