### PR TITLE
bnc#920089 - Changed dialog window size for entering static routes

### PR DESCRIPTION
**Pull request by damirporobic**
Bug 920089 - [yast2-network] - jj: The ncurses window for adding a static route is ridiculously small 

- Added MinWidth for dialog window
- Added proportional sizing for elements
- Added space between elements

### CODE REVIEW

**Comment by mchf** [comment]
codewise it looks good. However, there is some administrative stuff which should be done. Particularly, I mean updating changelog. If you agree, I can do it for you or pls do it yourself.

**Comment by damirporobic** [comment]
Can you point me to some documentation on how and where to do it? So I can do it in future by myself?

**Comment by mchf** [comment]
after some discussion in the team it was decided that I should do that for you. Details for contributing are described here http://yastgithubio.readthedocs.org/en/latest/contributing/. So, I'll check your patch against latest enterprise updates and merge it then.

**Comment by damirporobic** [comment]
I've tried to follow this guide, have I missed something? The changelog is not mentioned on this page.

**Comment by mchf** [comment]
yes, there is written you shouldn't fill that. I'll do it. I've misinformed you. It is just bcs of possible collisions with not released patches for issues reported by enterprise customers.

**Comment by mchf** [comment]
Please check updated PR as referenced above.

**Comment by mchf** [comment]
Merged in https://github.com/yast/yast-network/pull/391 together with changelog update. Thank you for the patch.

**Pull request closed without merging**
