### PR TITLE
Merged sle-12-sp3 into master

### PR DESCRIPTION
**Pull request by mchf**

### CODE REVIEW

**Comment by mvidner** [comment]
Travis is failing, apparently because of the firewall changes

**Comment by teclator** [comment]
@mchf I was creating a separate PR for https://github.com/yast/yast-network/pull/602/commits/720d9776a0239883430b22ef6e0df72aa13759af just with the same change so thnx ;)
It should be solved in yast/yast-yast2#674

**Comment by mchf** [comment]
@mvidner well, somehow fixed. Noticed @teclator for more proper fix in the widget definition.

**Comment by mchf** [comment]
@teclator thanks for the update

**Comment by mchf** [comment]
Thanks for the review

**Pull request merged**
