### PR TITLE
Adjusted help text. bnc#931478

### PR DESCRIPTION
**Pull request by mchf**

### CODE REVIEW

**Comment by jreidinger** [comment]
@mchf Problem is that I forgot to add rubocop to .travis.yml. Can you please add it and check if it passes? Thanks

**Comment by mvidner** [comment]
The text looks good. Have you omitted version + changelog intentionally?

**Comment by mchf** [comment]
@mvidner: yes, I think it is non critical and simple update which can be postponed.

**Comment by jreidinger** [comment]
LGTM

**Pull request merged**
