### PR TITLE
Enabled coveralls

### PR DESCRIPTION
**Pull request by mchf**
Follows https://github.com/yast/yast-network/pull/307 and https://github.com/yast/yast-network/pull/320

### CODE REVIEW

**Comment by mchf** [comment]
still an issue here ... coveralls do not send reports

**Comment by mvidner** [comment]
Yes. That is what I've been fixing yesterday. I think I will take your fix of firewall_stage1_proposal_test.rb and make #320 working.

**Comment by mchf** [comment]
May be we should merge our branches to avoid work duplication.

**Comment by mvidner** [comment]
Used 320 in the end. Thank you!

**Pull request closed without merging**
