### PR TITLE
[WIP] Drop replace direct access to LanItems::Items whenever it is possible.

### PR DESCRIPTION
**Pull request by mchf**

### CODE REVIEW

**Comment by teclator** [comment]
@mchf it was created during the HW, but probably you was not able to finish it, and even some class like NetDevice were added for having some kind of discussion. 

If we do not plan to work on it we probably should close it

**Comment by mchf** [comment]
well i work on it, but do not submit;-)

**Comment by teclator** [comment]
@mchf so please add a [WIP] to the current PR.

**Comment by mchf** [comment]
obsolete by https://github.com/yast/yast-network/pull/796

**Pull request closed without merging**
