### PR TITLE
Adapted to new device type detection API

### PR DESCRIPTION
**Pull request by mchf**
Mainly related to bnc#900383

### CODE REVIEW

**Comment by mvidner** [comment]
Oh, that's a lot more code than I've expected, I've thought you would pick just the first three, f69a315306b33f1315fb2b1ad8159b48e26ae1bb, f168d63990cc1e5cd6bbb963990e93a7c76cee50, and da9492e002c14d3e8b54d612188df60f46430618.
Were those not enough?

**Comment by mchf** [comment]
this is patch for the L3 bug. These three commits belongs there. For some reason this call of ```GetDeviceType``` was not catched by old build (autotools) way and I've built the patch successfully without that.  ```Code-11-SP4``` branch is going to be rebased on top (or merged) of Code-11-SP3 with this patch.

**Comment by mvidner** [comment]
I don't understand. This PR is meant to support merging https://github.com/yast/yast-yast2/pull/315 . Why does it have to include 2cb5790, a fix for bnc#551310?
(BTW, four commits are present twice:  4825954 and 78c56be, ... It is confusing me.)

**Comment by mvidner** [comment]
So this is a port of #100, #102, #104.

**Comment by mvidner** [comment]
LGTM.

**Comment by mchf** [comment]
Retested and works.

@mvidner: Thanks for review.

**Comment by mvidner** [comment]
@mchf something went wrong, this code is not in https://build.suse.de/package/show/SUSE:SLE-11-SP3:Update:Test/yast2-network

**Comment by mchf** [comment]
@mvidner thats bad ... Thanks for pointing that ... I'll check what's wrong.

**Pull request merged**
