### PR TITLE
lan_auto client returns value properly

### PR DESCRIPTION
**Pull request by imobach**
Fixes https://bugzilla.suse.com/show_bug.cgi?id=941449

### CODE REVIEW

**Comment by schubi2** [comment]
LGTM

**Comment by mchf** [comment]
thanks

**Comment by imobach** [comment]
@mchf @schubi2 Thanks

**Comment by schubi2** [comment]
LGTM again :-)

**Comment by kobliha** [comment]
Huh, bad bad mistake :)

@schubi2 @imobach Shouldn't we enhance AutoYast to report if *_auto returns nil? It's an error anyway, isn't it?

**Comment by imobach** [comment]
@schubi2 @kobliha I think so. Do you want to report to the user or just log the issue?

**Pull request merged**
