### PR TITLE
packaging: Require hostname

### PR DESCRIPTION
**Pull request by DimStar77**
Since the code calls /bin/hostname in multiple places, we really ought
to ensure /bin/hostname is present.

### CODE REVIEW

**Comment by DimStar77** [comment]
to be clear, this should fix issues like
  https://openqa.opensuse.org/tests/994890#step/installation/31

**Comment by imobachgs** [comment]
Thanks for the fix. Actually, we already had [a PR](https://github.com/yast/yast-yast2/pull/951) for the yast2.rpm package which should fix this issue too. But as we call hostname directly in yast2-network, I would say that your fix still applies.

Please, could you add the bug number [boo#1142595](https://bugzilla.opensuse.org/show_bug.cgi?id=1142595) to the changes file?

Thanks!

**Comment by DimStar77** [comment]
boo# added, force pushed

**Comment by imobachgs** [comment]
Thanks!

**Pull request merged**
