### PR TITLE
Write udev rules in non-{ssh/vnc} AY installation

### PR DESCRIPTION
**Pull request by mchf**
bnc#956605

### CODE REVIEW

**Comment by jreidinger** [comment]
LGTM. just do not forget to really do something with that fixme ;)

**Comment by mchf** [comment]
Thanks.

The fixme already has its PBI and I expect it will be planed for next sprint.

**Comment by schubi2** [comment]
LGTM too. I will start the testing for the mentioned bugs too.

**Comment by schubi2** [comment]
I do not see Micha in the IRC. So I am merging it for him and submitting the package.

**Pull request merged**
