### PR TITLE
Added dependency on yast2-proxy

### PR DESCRIPTION
**Pull request by mchf**
bnc#977953

### CODE REVIEW

**Comment by mvidner** [comment]
What about something better?
That is, moving [all proxy code](https://github.com/yast/yast-network/search?utf8=%E2%9C%93&q=proxy) to https://github.com/yast/yast-proxy .

**Comment by mchf** [comment]
Well, I'd propose to create a new PBI for moving rest of the proxy code. Lets PO plans it according his preferences. 

This can be a quick fix to let openQA to pass.

Acceptable?

**Comment by mvidner** [comment]
OK then, LGTM.

**Comment by mchf** [comment]
Thanks for review. PBI created. Merging.

**Comment by kobliha** [comment]
Just a hint: In next sprint of maybe even after that, I'd like to invest some time to minimize build dependencies and cycles to speed up the build process (requested by release managers). Additionally, we should think about dependencies that make the minimal installation bigger.

**Pull request merged**
