### PR TITLE
Merge SLE-12-SP1 into SP2

### PR DESCRIPTION
**Pull request by teclator**

### CODE REVIEW

**Comment by ancorgs** [comment]
Empty merge from an old branch to a newer one. That should mean cherry-pick. So I'm checking the 4 (four!) original pull requests covered by this:

* https://github.com/yast/yast-network/pull/429 It's a like a cherry-pick by @mchf. No surprise.
* https://github.com/yast/yast-network/pull/438 It's a backport by @teclator  Still right.
* https://github.com/yast/yast-network/pull/466 Authored by @schubi2. No mention of it being a backport or cherry-pick. No obviously equivalent PR to other branch found. I will investigate
* https://github.com/yast/yast-network/pull/478 Also a backport by @teclator.

I will check the third PR now, but please guys, in the future do the merge RIGHT AFTER the cherry-pick to save the reviewer from entering Sherlock Holmes mode.

**Comment by ancorgs** [comment]
Ok. I found out #466 was a backport of two pull requests: #414 and #420 

Please, when backporting:
  - If possible, use cherry-pick
  - In any case, mention it's a backport in the PR description and/or changes file.

**Comment by ancorgs** [comment]
My comments are about how things were done in the past. Regarding this particular merge: LGTM

**Comment by teclator** [comment]
@ancorgs thnx for the review, it was our fault to not merge it previously, sorry for make it hard to review.

**Pull request merged**
