### PR TITLE
Hostname dhcp fixes

### PR DESCRIPTION
**Pull request by mvidner**
https://bugzilla.suse.com/show_bug.cgi?id=1013605
https://trello.com/c/pN6f3kzr

### CODE REVIEW

**Comment by mvidner** [comment]
Now that we have https://github.com/openSUSE/linuxrc/pull/131
we can discard most of https://github.com/yast/yast-network/issues/476

**Comment by mchf** [comment]
I'd add also: https://github.com/yast/yast-https://github.com/yast/yast-network/pull/476/commits/b663a9276bcb9f1975b74091a737e2300ae7a709

**Comment by mvidner** [comment]
If I add https://github.com/yast/yast-network/pull/476/commits/b663a9276bcb9f1975b74091a737e2300ae7a709 then the test fails with
```
[   73s]   1) DHCLIENT_SET_HOSTNAME helpers LanItems#clear_set_hostname clears all DHCLIENT_SET_HOSTNAME options
[   73s]      Failure/Error: expect(ret).to eql dhclient_maps.keys
[   73s] 
[   73s]        expected: ["eth0", "eth1"]
[   73s]             got: [0, 1, 2]
[   73s] 
[   73s]        (compared using eql?)
[   73s]      # ./test/lan_items_helpers_test.rb:385:in `block (3 levels) in <top (required)>'
```

because I have not included the changes in LanItems#clear_set_hostname that the test depends on. If you think we should include this test, please adapt it.

**Comment by jreidinger** [comment]
well, what is status of test coverage of this changes? codewise LGTM

**Comment by mchf** [comment]
I'll add the test I mentioned a few lines above.

**Comment by jreidinger** [comment]
@mchf ok, so when test was added, it will be fine for me.

**Comment by mchf** [comment]
@mvidner I've modified https://github.com/yast/yast-network/pull/476 according this PR + https://github.com/yast/yast-network/pull/476/commits/b663a9276bcb9f1975b74091a737e2300ae7a709

Please merge one of this PRs and close the other if you're fine with any of them ;-) Thanks

**Pull request merged**
